name: Java CI
on: push

env:
   docker_username: ${{ github.actor }}
   docker_password: ${{ secrets.GITHUB_TOKEN }}
   GIT_COMMIT: ${{ github.GITHUB_SHA }}


jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: . 
  
  build: 
    needs: checkout
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
 
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
   
      - name: Fix Permissions
        run: chmod +x ci/*.sh

      - name: Build App
        run: ci/build-app.sh

      - name: Unit Tests
        run: ci/unit-test-app.sh
      
      - name: Upload Built Repo
        uses: actions/upload-artifact@v3
        with: 
          name: built-jar
          path: app/build/libs/app-0.1-all.jar

  docker-image:
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: built-jar
          path: . 

      - name: build docker
        run: ci/build-docker.sh
   
      - name: push docker
        run: ci/push-docker.sh
