name: Java CI
on: push
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Upload Repo
        uses: actions/upload-artifact@v3
        with:
          name: code
          path: . 
  
  build: 
    needs: checkout
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
 
      - name: Download code
        uses: actions/download-artifact@v3
        with:
          name: code
          path: .
   
      - name: Fix Permissions
        run: chmod +x ci/build-app.sh && chmod +x ci/unit-test-app.sh

      - name: Build App
        run: ci/build-app.sh

      - name: Unit Tests
        run: ci/unit-test-app.sh
      
      - name: Upload Built Repo
        uses: actions/upload-artifact@v3
        with: 
          name: code
          path: .
